services:
  postgres:
    image: postgres:17-alpine
    container_name: turnofacil-postgres

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - proxy-network

  backend:
    container_name: turnofacil-backend

    build:
      context: .
      dockerfile: backend-proyecto/backend-proyecto/Dockerfile

    env_file:
      - .env

    restart: unless-stopped

    depends_on:
      - postgres

    networks:
      - proxy-network

    ports:
      - "8080:8080"

    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/api/auth/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    container_name: turnofacil-frontend

    build:
      context: ./frontend-proyecto
      dockerfile: Dockerfile

    restart: unless-stopped

    networks:
      - proxy-network

volumes:
  postgres-data:

networks:
  proxy-network:
    external: true
