// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_proyecto.Config;

#nullable disable

namespace backend_proyecto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupPermission", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TENANT_READ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TENANT_UPDATE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "USER_READ"
                        },
                        new
                        {
                            Id = 4,
                            Name = "USER_CREATE"
                        },
                        new
                        {
                            Id = 5,
                            Name = "USER_UPDATE"
                        },
                        new
                        {
                            Id = 6,
                            Name = "USER_DELETE"
                        },
                        new
                        {
                            Id = 7,
                            Name = "STUDENT_READ"
                        },
                        new
                        {
                            Id = 8,
                            Name = "STUDENT_CREATE"
                        },
                        new
                        {
                            Id = 9,
                            Name = "STUDENT_UPDATE"
                        },
                        new
                        {
                            Id = 10,
                            Name = "STUDENT_DELETE"
                        },
                        new
                        {
                            Id = 11,
                            Name = "PROFESSOR_READ"
                        },
                        new
                        {
                            Id = 12,
                            Name = "PROFESSOR_CREATE"
                        },
                        new
                        {
                            Id = 13,
                            Name = "PROFESSOR_UPDATE"
                        },
                        new
                        {
                            Id = 14,
                            Name = "PROFESSOR_DELETE"
                        },
                        new
                        {
                            Id = 15,
                            Name = "PROFESSOR_ASSIGN_SPECIALITY"
                        },
                        new
                        {
                            Id = 16,
                            Name = "PROFESSOR_REMOVE_SPECIALITY"
                        },
                        new
                        {
                            Id = 17,
                            Name = "ACTIVITY_READ"
                        },
                        new
                        {
                            Id = 18,
                            Name = "ACTIVITY_CREATE"
                        },
                        new
                        {
                            Id = 19,
                            Name = "ACTIVITY_UPDATE"
                        },
                        new
                        {
                            Id = 20,
                            Name = "ACTIVITY_DELETE"
                        },
                        new
                        {
                            Id = 21,
                            Name = "SPECIALITY_READ"
                        },
                        new
                        {
                            Id = 22,
                            Name = "SPECIALITY_CREATE"
                        },
                        new
                        {
                            Id = 23,
                            Name = "SPECIALITY_UPDATE"
                        },
                        new
                        {
                            Id = 24,
                            Name = "SPECIALITY_DELETE"
                        },
                        new
                        {
                            Id = 25,
                            Name = "CLASS_READ"
                        },
                        new
                        {
                            Id = 26,
                            Name = "CLASS_CREATE"
                        },
                        new
                        {
                            Id = 27,
                            Name = "CLASS_UPDATE"
                        },
                        new
                        {
                            Id = 28,
                            Name = "CLASS_DELETE"
                        },
                        new
                        {
                            Id = 29,
                            Name = "RESERVATION_READ"
                        },
                        new
                        {
                            Id = 30,
                            Name = "RESERVATION_CREATE"
                        },
                        new
                        {
                            Id = 31,
                            Name = "RESERVATION_DELETE"
                        },
                        new
                        {
                            Id = 32,
                            Name = "RESERVATION_CHANGE_STATUS"
                        },
                        new
                        {
                            Id = 33,
                            Name = "PAYMENT_READ"
                        },
                        new
                        {
                            Id = 34,
                            Name = "PAYMENT_CREATE"
                        },
                        new
                        {
                            Id = 35,
                            Name = "PAYMENT_UPDATE"
                        },
                        new
                        {
                            Id = 36,
                            Name = "PAYMENT_DELETE"
                        },
                        new
                        {
                            Id = 37,
                            Name = "STUDENT_PLAN_READ"
                        },
                        new
                        {
                            Id = 38,
                            Name = "STUDENT_PLAN_CREATE"
                        },
                        new
                        {
                            Id = 39,
                            Name = "STUDENT_PLAN_UPDATE"
                        },
                        new
                        {
                            Id = 40,
                            Name = "STUDENT_PLAN_DELETE"
                        },
                        new
                        {
                            Id = 41,
                            Name = "TENANT_PLAN_READ"
                        },
                        new
                        {
                            Id = 42,
                            Name = "TENANT_PLAN_CREATE"
                        },
                        new
                        {
                            Id = 43,
                            Name = "TENANT_PLAN_UPDATE"
                        },
                        new
                        {
                            Id = 44,
                            Name = "TENANT_PLAN_DELETE"
                        },
                        new
                        {
                            Id = 45,
                            Name = "GROUP_READ"
                        },
                        new
                        {
                            Id = 46,
                            Name = "GROUP_CREATE"
                        },
                        new
                        {
                            Id = 47,
                            Name = "GROUP_UPDATE"
                        },
                        new
                        {
                            Id = 48,
                            Name = "GROUP_DELETE"
                        },
                        new
                        {
                            Id = 49,
                            Name = "GROUP_ASSIGN_USER"
                        },
                        new
                        {
                            Id = 50,
                            Name = "GROUP_REMOVE_USER"
                        },
                        new
                        {
                            Id = 51,
                            Name = "GROUP_ASSIGN_PERMISSION"
                        });
                });

            modelBuilder.Entity("UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("backend_proyecto.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("backend_proyecto.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("backend_proyecto.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TenantId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("backend_proyecto.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("backend_proyecto.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("backend_proyecto.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("backend_proyecto.Models.ProfessorSpeciality", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("integer");

                    b.HasKey("ProfessorId", "SpecialityId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("ProfessorSpecialities");
                });

            modelBuilder.Entity("backend_proyecto.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TenantId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("backend_proyecto.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("backend_proyecto.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MonthlyFeeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentPlanId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("backend_proyecto.Models.StudentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassesPerMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("StudentPlans");
                });

            modelBuilder.Entity("backend_proyecto.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MonthlyFeeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantPlanId");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("backend_proyecto.Models.TenantPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxProfessors")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TenantPlans");
                });

            modelBuilder.Entity("backend_proyecto.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GroupPermission", b =>
                {
                    b.HasOne("Group", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("UserGroup", b =>
                {
                    b.HasOne("Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_proyecto.Models.Activity", b =>
                {
                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("backend_proyecto.Models.Admin", b =>
                {
                    b.HasOne("backend_proyecto.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_proyecto.Models.Class", b =>
                {
                    b.HasOne("backend_proyecto.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Professor");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("backend_proyecto.Models.Payment", b =>
                {
                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_proyecto.Models.Professor", b =>
                {
                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany("Professors")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_proyecto.Models.ProfessorSpeciality", b =>
                {
                    b.HasOne("backend_proyecto.Models.Professor", "Professor")
                        .WithMany("ProfessorSpecialities")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("backend_proyecto.Models.Reservation", b =>
                {
                    b.HasOne("backend_proyecto.Models.Class", "Class")
                        .WithMany("Reservations")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("backend_proyecto.Models.Speciality", b =>
                {
                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("backend_proyecto.Models.Student", b =>
                {
                    b.HasOne("backend_proyecto.Models.StudentPlan", "StudentPlan")
                        .WithMany()
                        .HasForeignKey("StudentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany("Students")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentPlan");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_proyecto.Models.StudentPlan", b =>
                {
                    b.HasOne("backend_proyecto.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("backend_proyecto.Models.Tenant", b =>
                {
                    b.HasOne("backend_proyecto.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyecto.Models.TenantPlan", "TenantPlan")
                        .WithMany()
                        .HasForeignKey("TenantPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");

                    b.Navigation("TenantPlan");
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("backend_proyecto.Models.Class", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("backend_proyecto.Models.Professor", b =>
                {
                    b.Navigation("ProfessorSpecialities");
                });

            modelBuilder.Entity("backend_proyecto.Models.Tenant", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
